# CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
CONFIG_ZMK_IDLE_TIMEOUT=900000

# Display (OLED)
# CONFIG_ZMK_DISPLAY=y
# CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
# CONFIG_ZMK_DISPLAY_BLANK_TIMEOUT=15000
# CONFIG_ZMK_DISPLAY_INVERT=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
# CONFIG_ZMK_WIDGET_WPM_STATUS=n


# BLE settings
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# CONFIG_BT_CTLR_TX_PWR_MINUS_8=y
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=24
# CONFIG_BT_PERIPHERAL_PREF_LATENCY=30

# Debouncing
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7
